package com.pojo;
// Generated 6 Dec, 2017 11:24:57 AM by Hibernate Tools 3.6.0.Final

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer ciid;
	private State state;
	private String ciname;

	public City() {
	}

	public City(State state, String ciname) {
		this.state = state;
		this.ciname = ciname;
	}

	public Integer getCiid() {
		return this.ciid;
	}

	public void setCiid(Integer ciid) {
		this.ciid = ciid;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getCiname() {
		return this.ciname;
	}

	public void setCiname(String ciname) {
		this.ciname = ciname;
	}

}
