package com.pojo;
// Generated 6 Dec, 2017 11:24:57 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State implements java.io.Serializable {

	private Integer sid;
	private Country country;
	private String sname;
	private Set cities = new HashSet(0);

	public State() {
	}

	public State(Country country, String sname, Set cities) {
		this.country = country;
		this.sname = sname;
		this.cities = cities;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public Set getCities() {
		return this.cities;
	}

	public void setCities(Set cities) {
		this.cities = cities;
	}

}
